url: https://bitgapps.io
title: BiTGApps | Google Apps Package
email: info@bitgapps.io
description: BiTGApps is a customized Google Apps Package to sideload Google Apps in Custom Android OS. Supports Android 16.0 to 7.1.x with regular updates and bugs fixed.
keywords: android, google, apps, google apps, google apps android, google apps package, gapps, gapps download, gapps package, gapps package android, gapps android, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, opengapps, mindthegapps, bit gapps, bitgapps, bitgapp, nikgapps, flamegapps, litegapps, arm, arm64, core, mini, omni, roar, nano, atom, pico, full, tint, ksu, kernelsu, kernel, android experience, magisk, magisk gapps, gapps systemless
logo: https://bitgapps.io/images/1cecUb3.png
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-minimal
